"""Add used_by_mac field to Voucher

Revision ID: 0f489ec461e0
Revises: 6436565be49d
Create Date: 2025-03-30 14:28:47.575526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f489ec461e0'
down_revision = '6436565be49d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voucher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_name', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voucher', schema=None) as batch_op:
        batch_op.drop_column('plan_name')

    # ### end Alembic commands ###
