"""Add upload tracking to voucher_batch

Revision ID: 21d6ed543a89
Revises: 75905a29a056
Create Date: 2025-04-08 23:45:26.317300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21d6ed543a89'
down_revision = '75905a29a056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voucher_batch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voucher_batch', schema=None) as batch_op:
        batch_op.drop_column('upload_date')
        batch_op.drop_column('upload_status')

    # ### end Alembic commands ###
