"""Add created_on_router_id to voucher

Revision ID: 2cb37b188077
Revises: e588c3f6955f
Create Date: 2025-05-05 13:36:33.362337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cb37b188077'
down_revision = 'e588c3f6955f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voucher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on_router_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'mikro_tik_router', ['created_on_router_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voucher', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_on_router_id')

    # ### end Alembic commands ###
