"""Add used_by_mac field to Voucher

Revision ID: 6436565be49d
Revises: 5349bb08f1d4
Create Date: 2025-03-30 14:24:04.837903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6436565be49d'
down_revision = '5349bb08f1d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voucher_batch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voucher_batch', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
