"""Add plan_name to Voucher

Revision ID: 7086f5d5a8f4
Revises: 0f489ec461e0
Create Date: 2025-03-30 14:36:05.408428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7086f5d5a8f4'
down_revision = '0f489ec461e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voucher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_cap', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voucher', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('data_cap')

    # ### end Alembic commands ###
