"""Add used_by_mac field to Voucher

Revision ID: 73c55799f058
Revises: 4862556eb137
Create Date: 2025-03-30 11:53:49.832611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73c55799f058'
down_revision = '4862556eb137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voucher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used_by_mac', sa.String(length=50), nullable=True))
        batch_op.alter_column('used_mb',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voucher', schema=None) as batch_op:
        batch_op.alter_column('used_mb',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.drop_column('used_by_mac')

    # ### end Alembic commands ###
