"""Add RouterOS version and login_mode to MikroTikRouter

Revision ID: 75905a29a056
Revises: 9496f97d681b
Create Date: 2025-04-05 20:34:50.693841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75905a29a056'
down_revision = '9496f97d681b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mikro_tik_router', schema=None) as batch_op:
        batch_op.add_column(sa.Column('routeros_version', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('login_mode', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mikro_tik_router', schema=None) as batch_op:
        batch_op.drop_column('login_mode')
        batch_op.drop_column('routeros_version')

    # ### end Alembic commands ###
