"""3

Revision ID: 778a0a8e2e43
Revises: 7086f5d5a8f4
Create Date: 2025-04-02 21:51:38.299810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '778a0a8e2e43'
down_revision = '7086f5d5a8f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate_limit', sa.String(length=50), nullable=True))

    with op.batch_alter_table('user_usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timed_out', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_usage', schema=None) as batch_op:
        batch_op.drop_column('timed_out')

    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_column('rate_limit')

    # ### end Alembic commands ###
