"""Add timestamp to Payment model

Revision ID: 9496f97d681b
Revises: 542c883b02a9
Create Date: 2025-04-03 02:41:32.749990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9496f97d681b'
down_revision = '542c883b02a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mikro_tik_router', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_port', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mikro_tik_router', schema=None) as batch_op:
        batch_op.drop_column('api_port')

    # ### end Alembic commands ###
