"""Add IPChangeLog model

Revision ID: d5ff18d988c9
Revises: 21d6ed543a89
Create Date: 2025-04-11 09:39:24.115053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5ff18d988c9'
down_revision = '21d6ed543a89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_change_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('router_id', sa.Integer(), nullable=False),
    sa.Column('old_ip', sa.String(length=100), nullable=True),
    sa.Column('new_ip', sa.String(length=100), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['router_id'], ['mikro_tik_router.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ip_change_logs')
    # ### end Alembic commands ###
