"""Add mikrotik_profile to Plan

Revision ID: e588c3f6955f
Revises: d5ff18d988c9
Create Date: 2025-04-16 22:21:05.792707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e588c3f6955f'
down_revision = 'd5ff18d988c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mikrotik_profile', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_column('mikrotik_profile')

    # ### end Alembic commands ###
