"""Add timestamp to Payment model

Revision ID: f7664cefc73a
Revises: 778a0a8e2e43
Create Date: 2025-04-02 21:55:12.335171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7664cefc73a'
down_revision = '778a0a8e2e43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
